class EnvVariableFile(object):
	T_WORK = '/ade/kgurupra_dte8028/oracle/work/build_run_robot1/../'
	VIEW_ROOT = '/ade/kgurupra_dte8028'
	BROWSERTYPE = 'firefox'  ########################For OID info################################################
	
	OID_HOST = 'slc06xgk.us.oracle.com'
	OID_PORT = '15635'
	OID_SSL_PORT = '22718'
	OID_ADMIN = 'cn=orcladmin'
	OID_ADMIN_PASSWORD = 'welcome1'
	
	# # ########################For OHS&WG info################################################
	# OHS_HOST = 'idmr2ps3.us.oracle.com'
	# OHS_INSTANCE_HOME = '/scratch/amywork/ohs9743/user_projects/domains/OHSDomain_standa2'
	# OHS_COMPONENT_NAME = 'standal_ohs2'
	# OHS_MW_HOME = '/scratch/amywork/ohs9743'
	# OHS_WL_HOME = '/scratch/amywork/ohs9743/wlserver'
	# OHS_COMMON_ORACLE_HOME = '/scratch/amywork/ohs9743/oracle_common'
	# OHS_ADMIN_PORT = '1111'
	# OHS_LISTEN_PORT = '23191'
	# OHS_SSL_LISTEN_PORT = '3333'
	# OHS_WLS_PWD = 'welcome1'
	# WEBGATE_ID = 'oam_12wg149'
	# OHS_WG_INST_HOME = '/scratch/amywork/ohs9743/user_projects/domains/OHSDomain_standa2/config/fmwconfig/components/OHS/instances/standal_ohs2/webgate/config'
	# OHS_INSTANCE_NM_START = '/scratch/amywork/ohs9743/user_projects/domains/OHSDomain_standa2/bin/startNodeManager.sh'
	# OHS_INSTANCE_NM_STOP = '/scratch/amywork/ohs9743/user_projects/domains/OHSDomain_standa2/bin/stopNodeManager.sh'
	# OHS_INSTANCE_BIN_START = '/scratch/amywork/ohs9743/user_projects/domains/OHSDomain_standa2/bin/startComponent.sh'
	# OHS_INSTANCE_BIN_STOP = '/scratch/amywork/ohs9743/user_projects/domains/OHSDomain_standa2/bin/stopComponent.sh'
	# OHS_INSTANCE_BIN_START_CMD = '/scratch/amywork/ohs9743/user_projects/domains/OHSDomain_standa2/bin/startComponent.sh standal_ohs2'
	# OHS_INSTANCE_BIN_STOP_CMD = '/scratch/amywork/ohs9743/user_projects/domains/OHSDomain_standa2/bin/stopComponent.sh standal_ohs2'
	# RESOURCE_URL = 'http://slc03sfc.us.oracle.com:2222/index.html'
	# RESOURCE_APPURL = 'http://slc03sfc.us.oracle.com:2222/app1/pages/Sample.jsp'
	#
	# ########################For OAM sever info################################################
	OHS_HOST = 'den00rum.us.oracle.com'
	OHS_INSTANCE_HOME = '/scratch/kgurupra/A1/ohs3941/user_projects/domains/OHSDomain_standa2'
	OHS_COMPONENT_NAME = 'standal_ohs2'
	OHS_MW_HOME = '/scratch/kgurupra/A1/ohs3941'
	OHS_WL_HOME = '/scratch/kgurupra/A1/ohs3941/wlserver'
	OHS_COMMON_ORACLE_HOME = '/scratch/kgurupra/A1/ohs3941/oracle_common'
	OHS_ADMIN_PORT = '1111'
	OHS_LISTEN_PORT = '7777'
	OHS_SSL_LISTEN_PORT = '3333'
	OHS_WLS_PWD = 'welcome1'
	WEBGATE_ID = 'oam_12wg3697'
	OHS_WG_INST_HOME = '/scratch/kgurupra/A1/ohs3941/user_projects/domains/OHSDomain_standa2/config/fmwconfig/components/OHS/instances/standal_ohs2/webgate/config'
	OHS_INSTANCE_NM_START = '/scratch/kgurupra/A1/ohs3941/user_projects/domains/OHSDomain_standa2/bin/startNodeManager.sh'
	OHS_INSTANCE_NM_STOP = '/scratch/kgurupra/A1/ohs3941/user_projects/domains/OHSDomain_standa2/bin/stopNodeManager.sh'
	OHS_INSTANCE_BIN_START = '/scratch/kgurupra/A1/ohs3941/user_projects/domains/OHSDomain_standa2/bin/startComponent.sh'
	OHS_INSTANCE_BIN_STOP = '/scratch/kgurupra/A1/ohs3941/user_projects/domains/OHSDomain_standa2/bin/stopComponent.sh'
	OHS_INSTANCE_BIN_START_CMD = '/scratch/kgurupra/A1/ohs3941/user_projects/domains/OHSDomain_standa2/bin/startComponent.sh standal_ohs2'
	OHS_INSTANCE_BIN_STOP_CMD = '/scratch/kgurupra/A1/ohs3941/user_projects/domains/OHSDomain_standa2/bin/stopComponent.sh standal_ohs2'
	RESOURCE_URL = 'http://den02mpu.us.oracle.com:2222/index.html'
	RESOURCE_APPURL = 'http://den02mpu.us.oracle.com:2222/app1/pages/Sample.jsp'
	
	# ########################For OHS&WG info################################################
	OAM_ADMSERVER_HOST = 'den00rum.us.oracle.com'
	OAM_ADMSERVER_PORT = '7001'
	OAM_ADMSERVER_SSLPORT = '23009'
	OAM_MNGSERVER_PORT = '14100'
	OAM_MNGSERVER_SSLPORT = '20261'
	OAM_MNGSERVER_NAME = 'oam_server1'
	OAM_ADMIN_USER = 'weblogic'
	OAM_ADMIN_PWD = 'welcome1'
	OAM_WLS_USER = 'weblogic'
	OAM_WLS_PWD = 'welcome1'
	OAM_MW_HOME = '/scratch/kgurupra/A1/mw5470'
	OAM_ORACLE_HOME = '/scratch/kgurupra/A1/mw5470/idm'
	OAM_DOMAIN_HOME = '/scratch/kgurupra/A1/mw5470/user_projects/domains/WLS_IDM'
	OAM_WLS_HOME = '/scratch/kgurupra/A1/mw5470/wlserver'
	JKSSTORE_PATH = '/scratch/kgurupra/A1/mw5470/wlserver/server/lib/DemoTrust.jks'
	WLS_CONSOLE_URL = 'den02mpu.us.oracle.com/22456/console'
	OAM_CONSOLE_URL = 'den02mpu.us.oracle.com/22456/oamconsole'
	OAM_ID_STORE = 'UserIdentityStore1'
	
	# OAM_ADMSERVER_HOST = 'den02mpu.us.oracle.com'
	# OAM_ADMSERVER_PORT = '22456'
	# OAM_ADMSERVER_SSLPORT = '17093'
	# OAM_MNGSERVER_PORT = '18180'
	# OAM_MNGSERVER_SSLPORT = '21645'
	# OAM_MNGSERVER_NAME = 'oam_server1'
	# OAM_ADMIN_USER = 'weblogic'
	# OAM_ADMIN_PWD = 'weblogic1'
	# OAM_WLS_USER = 'weblogic'
	# OAM_WLS_PWD = 'weblogic1'
	# OAM_MW_HOME = '/scratch/aime1/work/mw2501'
	# OAM_ORACLE_HOME = '/scratch/aime1/work/mw2501/idm'
	# OAM_DOMAIN_HOME = '/scratch/aime1/work/mw2501/user_projects/domains/WLS_IDM'
	# OAM_WLS_HOME = '/scratch/aime1/work/mw2501/wlserver'
	# JKSSTORE_PATH = '/scratch/aime1/work/mw2501/wlserver/server/lib/DemoTrust.jks'
	# WLS_CONSOLE_URL = 'adc00sax.us.oracle.com/18196/console'
	# OAM_CONSOLE_URL = 'adc00sax.us.oracle.com/18196/oamconsole'
	# OAM_ID_STORE = 'UserIdentityStore1'


# OHS_HOST = 'slc03sfc.us.oracle.com'
# OHS_INSTANCE_HOME = '/scratch/amywork/ohs9743/user_projects/domains/OHSDomain_standa2'
# OHS_COMPONENT_NAME = 'standal_ohs2'
# OHS_MW_HOME = '/scratch/amywork/ohs9743'
# OHS_WL_HOME = '/scratch/amywork/ohs9743/wlserver'
# OHS_COMMON_ORACLE_HOME = '/scratch/amywork/ohs9743/oracle_common'
# OHS_ADMIN_PORT = '1111'
# OHS_LISTEN_PORT = '2222'
# OHS_SSL_LISTEN_PORT = '3333'
# OHS_WLS_PWD = 'welcome1'
# WEBGATE_ID = 'oam_12wg149'
# OHS_WG_INST_HOME = '/scratch/amywork/ohs9743/user_projects/domains/OHSDomain_standa2/config/fmwconfig/components/OHS/instances/standal_ohs2/webgate/config'
# OHS_INSTANCE_NM_START = '/scratch/amywork/ohs9743/user_projects/domains/OHSDomain_standa2/bin/startNodeManager.sh'
# OHS_INSTANCE_NM_STOP = '/scratch/amywork/ohs9743/user_projects/domains/OHSDomain_standa2/bin/stopNodeManager.sh'
# OHS_INSTANCE_BIN_START = '/scratch/amywork/ohs9743/user_projects/domains/OHSDomain_standa2/bin/startComponent.sh'
# OHS_INSTANCE_BIN_STOP = '/scratch/amywork/ohs9743/user_projects/domains/OHSDomain_standa2/bin/stopComponent.sh'
# OHS_INSTANCE_BIN_START_CMD = '/scratch/amywork/ohs9743/user_projects/domains/OHSDomain_standa2/bin/startComponent.sh standal_ohs2'
# OHS_INSTANCE_BIN_STOP_CMD = '/scratch/amywork/ohs9743/user_projects/domains/OHSDomain_standa2/bin/stopComponent.sh standal_ohs2'
# RESOURCE_URL = 'http://slc03sfc.us.oracle.com:2222/index.html'
# RESOURCE_APPURL = 'http://slc03sfc.us.oracle.com:2222/app1/pages/Sample.jsp'
# IDENTITYPROVIDER='IDSPROFILE-OUD_Amy'
#
# ########################For OAM sever info################################################
# OAM_ADMSERVER_HOST = 'slc03sfc.us.oracle.com'
# OAM_ADMSERVER_PORT = '17416'
# OAM_ADMSERVER_SSLPORT = '22290'
# OAM_MNGSERVER_PORT = '17647'
# OAM_MNGSERVER_SSLPORT = '17493'
# OAM_MNGSERVER_NAME = 'oam_server1'
# OAM_ADMIN_USER = 'oamAdmin'
# OAM_ADMIN_PWD = 'Welcome1'
# OAM_WLS_USER = 'oamAdmin'
# OAM_WLS_PWD = 'Welcome1'
# OAM_MW_HOME = '/scratch/amywork/mw8296'
# OAM_ORACLE_HOME = '/scratch/amywork/mw8296/idm'
# OAM_DOMAIN_HOME = '/scratch/amywork/mw8296/user_projects/domains/WLS_IDM'
# OAM_WLS_HOME = '/scratch/amywork/mw8296/wlserver'
# JKSSTORE_PATH = '/scratch/amywork/mw8296/wlserver/server/lib/DemoTrust.jks'
# WLS_CONSOLE_URL = 'slc03sfc.us.oracle.com/17416/console'
# OAM_CONSOLE_URL = 'slc03sfc.us.oracle.com/17416/oamconsole'

# ########################For OHS&WG info################################################
#     OHS_HOST = 'slc07jgj.us.oracle.com'
#     OHS_INSTANCE_HOME = '/scratch/amywork/ohs8447/user_projects/domains/OHSDomain_standa2'
#     OHS_COMPONENT_NAME = 'standal_ohs2'
#     OHS_MW_HOME = '/scratch/amywork/ohs8447'
#     OHS_WL_HOME = '/scratch/amywork/ohs8447/wlserver'
#     OHS_COMMON_ORACLE_HOME = '/scratch/amywork/ohs8447/oracle_common'
#     OHS_ADMIN_PORT = '1111'
#     OHS_LISTEN_PORT = '2222'
#     OHS_SSL_LISTEN_PORT = '3333'
#     OHS_WLS_PWD = 'welcome1'
#     WEBGATE_ID = 'ThreeLeggedWG'
#     OHS_WG_INST_HOME = '/scratch/amywork/ohs8447/user_projects/domains/OHSDomain_standa2/config/fmwconfig/components/OHS/instances/standal_ohs2/webgate/config'
#     OHS_INSTANCE_NM_START = '/scratch/amywork/ohs8447/user_projects/domains/OHSDomain_standa2/bin/startNodeManager.sh'
#     OHS_INSTANCE_NM_STOP = '/scratch/amywork/ohs8447/user_projects/domains/OHSDomain_standa2/bin/stopNodeManager.sh'
#     OHS_INSTANCE_BIN_START = '/scratch/amywork/ohs8447/user_projects/domains/OHSDomain_standa2/bin/startComponent.sh'
#     OHS_INSTANCE_BIN_STOP = '/scratch/amywork/ohs8447/user_projects/domains/OHSDomain_standa2/bin/stopComponent.sh'
#     OHS_INSTANCE_BIN_START_CMD = '/scratch/amywork/ohs8447/user_projects/domains/OHSDomain_standa2/bin/startComponent.sh standal_ohs2'
#     OHS_INSTANCE_BIN_STOP_CMD = '/scratch/amywork/ohs8447/user_projects/domains/OHSDomain_standa2/bin/stopComponent.sh standal_ohs2'
#     RESOURCE_URL = 'http://slc07jgj.us.oracle.com:2222/index.html'
#     RESOURCE_APPURL = 'http://slc07jgj.us.oracle.com:2222/app1/pages/Sample.jsp'
# #
# ########################For OAM sever info################################################
#     OAM_ADMSERVER_HOST = 'slc07jgj.us.oracle.com'
#     OAM_ADMSERVER_PORT = '20192'
#     OAM_ADMSERVER_SSLPORT = '20981'
#     OAM_MNGSERVER_PORT = '20053'
#     OAM_MNGSERVER_SSLPORT = '21283'
#     OAM_MNGSERVER_NAME = 'oam_server1'
#     OAM_ADMIN_USER = 'oamAdmin'
#     OAM_ADMIN_PWD = 'Welcome1'
#     OAM_WLS_USER = 'oamAdmin'
#     OAM_WLS_PWD = 'Welcome1'
#     OAM_MW_HOME = '/scratch/amywork/mw7624'
#     OAM_ORACLE_HOME = '/scratch/amywork/mw7624/idm'
#     OAM_DOMAIN_HOME = '/scratch/amywork/mw7624/user_projects/domains/WLS_IDM'
#     OAM_WLS_HOME = '/scratch/amywork/mw7624/wlserver'
#     JKSSTORE_PATH = '/scratch/amywork/mw7624/wlserver/server/lib/DemoTrust.jks'
#     WLS_CONSOLE_URL = 'slc07jgj.us.oracle.com/20192/console'
#     OAM_CONSOLE_URL = 'slc07jgj.us.oracle.com/20192/oamconsole'

# ########################For OAM sever info################################################
#
# OAM_ADMSERVER_HOST = 'den02mpu.us.oracle.com'
# OAM_ADMSERVER_PORT = '24153'
# OAM_ADMSERVER_SSLPORT = '20139'
# OAM_MNGSERVER_PORT = '21010'
# OAM_MNGSERVER_SSLPORT = '18389'
# OAM_MNGSERVER_NAME = 'oam_server1'
# OAM_ADMIN_USER = 'oamAdminUser'
# OAM_ADMIN_PWD = 'welcome1'
# OAM_WLS_USER = 'oamAdminUser'
# OAM_WLS_PWD = 'welcome1'
# OAM_MW_HOME = '/scratch/kgurupra/A1/mw8368'
# OAM_ORACLE_HOME = '/scratch/kgurupra/A1/mw8368/idm'
# OAM_DOMAIN_HOME = '/scratch/kgurupra/A1/mw8368/user_projects/domains/WLS_IDM'
# OAM_WLS_HOME = '/scratch/kgurupra/A1/mw8368/wlserver'
# JKSSTORE_PATH = '/scratch/kgurupra/A1/mw8368/wlserver/server/lib/DemoTrust.jks'
# WLS_CONSOLE_URL = 'den02mpu.us.oracle.com/24153/console'
# OAM_CONSOLE_URL = 'den02mpu.us.oracle.com/24153/oamconsole'

########################For DATABASE################################################

	DATABASE_HOST = 'slc06xgk.us.oracle.com'
	DATABASE_SID = 'db2647'
	DATABASE_PORT = '11236'
	RCU_OIM = '%RCU_OIM%'
	RCU_OIM_PASSWD = '%RCU_OIM_PASSWD%'
########################FOR OUD Config################################################

	OUD_HOST = '%OUD_HOST%'
	OUD_PORT = '%OUD_PORT%'
	OUD_ADMIN_USER = '%OUD_ADMIN_USER%'
	OUD_ADMIN_PWD = '%OUD_ADMIN_PWD%'
	OUD_SSL_PORT = '%OUD_SSL_PORT%'
	OUD_BASE_DN = '%OUD_BASE_DN%'
########################Others################################################

	FIREFOX_BIN = '/ade/kgurupra_dte8028/oracle/work/INSTALL_FIREFOX14/../firefox/firefox'

######################## For  FIAT ################################################
	MDC_ATTR = '/ade/kgurupra_dte2941/oracle/work/config.properties'
########################For HAPROXY LBR INFO################################################
	DC1_HAPROXY_INSTALL_LOC = '/scratch/kgurupra/APR14/test_proxy1'
	DC1_HAPROXY_LBR_HOST = 'slc12ldo.us.oracle.com'
	DC1_HAPROXY_CONFIG_FILE = '/scratch/kgurupra/APR14/test_proxy1/haproxy/sbin/haproxy_single.cfg'
	DC1_LBR_PORT = '17777'
	DC1_OHS1_HOSTNAME = 'slc12ldo.us.oracle.com'
	DC1_OHS1_PORT = '2222'
	DC1_OHS2_HOSTNAME = 'slc09cor.us.oracle.com'
	DC1_OHS2_PORT = '2222'
	######################## For  FIAT ################################################
	MDC_ATTR = '/ade/kgurupra_dte2941/oracle/work/config.properties'
	########################For DATABASE BLOCK ################################################
	DC1_DB_HOSTNAME = 'slc12ldo.us.oracle.com'
	DC1_DB_ORACLE_HOME = '/scratch/kgurupra/APR14/db1246'
	DC1_DB_ORACLE_SID = 'db1246'
	DC1_DB_GLOBAL_DB_NAME = 'db1246.us.oracle.com'
	DC1_DB_DB_PORT = '15581'
	DC1_DB_SYS_PASSWORD = 'welcome1'
	DC1_DB_CONNECTION_STRING = 'slc12ldo.us.oracle.com:15581:db1246'
	########################For RCUPHASE  BLOCK ################################################
	DC1_COMMON_ORACLE_HOME = '/scratch/kgurupra/APR14/mw5651/oracle_common'
	DC1_DB_OAM_SCHEMANAME = 'db1246_OAM'
	########################For IDM_NEXTGEN_CONFIG1 BLOCK ################################################
	DC1_OAM_PROXYPORT = '5575'
	DC1_WLS_USER = 'weblogic'
	DC1_WLS_PWD = 'weblogic1'
	DC1_WLS_DOMAIN_NAME = 'WLS_IDM'
	DC1_MW_HOME = '/scratch/kgurupra/APR14/mw5651'
	DC1_WL_HOME = '/scratch/kgurupra/APR14/mw5651/wlserver'
	DC1_ORACLE_HOME = '/scratch/kgurupra/APR14/mw5651/idm'
	DC1_WLS_DOMAIN_HOME = '/scratch/kgurupra/APR14/mw5651/user_projects/domains/WLS_IDM'
	DC1_WLS_CONSOLE_PORT = '17800'
	DC1_WLS_CONSOLE_SSLPORT = '17978'
	DC1_HOSTNAME = 'slc12ldo.us.oracle.com'
	DC1_ADMIN_SERVER_NAME = 'AdminServer'
	DC1_COMMON_ORACLE_HOME = '/scratch/kgurupra/APR14/mw5651/oracle_common'
	DC1_SHUTDOWN_SCRIPT = '/scratch/kgurupra/APR14/mw5651/idm/shutdown.csh'
	DC1_OAM_MNGSERVER_NAME = 'oam_server1'
	DC1_OAM_MNGSERVER_PORT = '15729'
	DC1_OAM_MNGSERVER_SSL_PORT = '16137'
	DC1_OAMPOL_MNGSERVER_NAME = 'oam_policy_mgr1'
	DC1_OAMPOL_MNGSERVER_PORT = '16489'
	DC1_OAMPOL_MNGSERVER_SSL_PORT = '24549'
	########################For OID info################################################
	########################For 11g OHS&WG info################################################
	DC1_WEBT11g_WL_HOME = '/scratch/kgurupra/APR14/mw6608/wlserver_10.3'
	DC1_WEBT11g_JDK_HOME = '/net/adcnas418/export/farm_fmwqa/java/linux64/jdk7u80'
	########################For JRF_INSTALL ################################################
	DC1_OHS12C_WGID = 'DC1WG'
	DC1_WG_OHS_PORT = '2222'
	DC1_OHS12C_HOSTNAME = 'slc12ldo.us.oracle.com'
	DC1_RREG_OUTPUT =''
	########################For JRF_INSTALL ################################################
	DC1_JRF_INSTALL_JDK_HOME = '/ade_autofs/gd29_3rdparty/JDK8_MAIN_LINUX.X64.rdd/LATEST/jdk8/'
	DC1_JRF_INSTALL_MW_HOME = '/scratch/kgurupra/APR14/mw4522/wlserver'
	DC1_JRF_SHIPHOME = '/ade/kgurupra_dte2941/oracle/work/JRF_INSTALL/stage/fmw_12.2.1.3.0_infrastructure_generic.jar'
	########################For FMW_OHS_INST1 ################################################
	DC1_OHS12C_ORACLE_HOME = '/scratch/kgurupra/APR14/ohs5082'
	DC1_OHS12C_INSTALL_TYPE = 'STANDALONE'
	########################For FMW_OHS_INST1 ################################################
	DC1_OHS12C_ORACLE_HOME = '/scratch/kgurupra/APR14/ohs5082'
	DC1_OHS12C_INSTALL_TYPE = 'STANDALONE'
	DC1_NODEMGR_PORT = '5556'
	########################For Create_Standalone_Instance ################################################
	DC1_OHS12C_WLS_USER = 'weblogic'
	DC1_OHS12C_WLS_PWD = 'welcome1'
	DC1_OHS12C_WLS_DOMAIN_NAME = 'OHSDomain_standa2'
	DC1_OHS_INSTANCE_NAME = 'standal_ohs2'
	DC1_OHS12C_WLS_DOMAIN_HOME = '/scratch/kgurupra/APR14/ohs5082/user_projects/domains/OHSDomain_standa2'
	DC1_OHS12C_MW_HOME = '/scratch/kgurupra/APR14/ohs5082'
	DC1_OHS12C_ADMIN_PORT = '1111'
	DC1_OHS12C_LISTEN_PORT = '2222'
	DC1_OHS12C_SSL_LISTEN_PORT = '3333'
	######################## For  FIAT ################################################
	MDC_ATTR = '/ade/kgurupra_dte2941/oracle/work/config.properties'
	########################For DATABASE BLOCK ################################################
	DC2_DB_HOSTNAME = 'slc09cor.us.oracle.com'
	DC2_DB_ORACLE_HOME = '/scratch/kgurupra/APR14/db6075'
	DC2_DB_ORACLE_SID = 'db6075'
	DC2_DB_GLOBAL_DB_NAME = 'db6075.us.oracle.com'
	DC2_DB_DB_PORT = '11378'
	DC2_DB_SYS_PASSWORD = 'welcome1'
	DC2_DB_CONNECTION_STRING = 'slc09cor.us.oracle.com:11378:db6075'
	########################For RCUPHASE  BLOCK ################################################
	DC2_COMMON_ORACLE_HOME = '/scratch/kgurupra/APR14/mw33/oracle_common'
	DC2_DB_OAM_SCHEMANAME = 'db6075_OAM'
	########################For IDM_NEXTGEN_CONFIG1 BLOCK ################################################
	DC2_OAM_PROXYPORT = '5575'
	DC2_WLS_USER = 'weblogic'
	DC2_WLS_PWD = 'weblogic1'
	DC2_WLS_DOMAIN_NAME = 'WLS_IDM'
	DC2_MW_HOME = '/scratch/kgurupra/APR14/mw33'
	DC2_WL_HOME = '/scratch/kgurupra/APR14/mw33/wlserver'
	DC2_ORACLE_HOME = '/scratch/kgurupra/APR14/mw33/idm'
	DC2_WLS_DOMAIN_HOME = '/scratch/kgurupra/APR14/mw33/user_projects/domains/WLS_IDM'
	DC2_WLS_CONSOLE_PORT = '21226'
	DC2_WLS_CONSOLE_SSLPORT = '15458'
	DC2_HOSTNAME = 'slc09cor.us.oracle.com'
	DC2_ADMIN_SERVER_NAME = 'AdminServer'
	DC2_COMMON_ORACLE_HOME = '/scratch/kgurupra/APR14/mw33/oracle_common'
	DC2_SHUTDOWN_SCRIPT = '/scratch/kgurupra/APR14/mw33/idm/shutdown.csh'
	DC2_FRONT_END_PORT =''
	DC2_FRONT_END_HOST =''
	DC2_OAM_MNGSERVER_NAME = 'oam_server1'
	DC2_OAM_MNGSERVER_PORT = '24618'
	DC2_OAM_MNGSERVER_SSL_PORT = '15011'
	DC2_OAMPOL_MNGSERVER_NAME = 'oam_policy_mgr1'
	DC2_OAMPOL_MNGSERVER_PORT = '18230'
	DC2_OAMPOL_MNGSERVER_SSL_PORT = '24786'
	DC2_OAM_MNGSERVER2_NAME =''
	DC2_OAM_MNGSERVER2_PORT =''
	DC2_OAM_MNGSERVER2_SSL_PORT =''
	DC2_OAMPOL_MNGSERVER2_NAME =''
	DC2_OAMPOL_MNGSERVER2_PORT =''
	DC2_OAMPOL_MNGSERVER2_SSL_PORT =''
	########################For OID info################################################
	DC2_OID_DOMAIN_HOME =''
	DC2_OID_HOSTNAME =''
	DC2_LDAP_SSL_PORT =''
	DC2_LDAP_NONSSL_PORT =''
	DC2_OID_INSTANCE_HOME =''
	DC2_OID_ADMIN_PASSWORD =''
	DC2_OID_USER =''
	DC2_OID_NAMESPACE =''
	########################For 11g OHS&WG info################################################
	DC2_WEBT11g_WL_HOME = '/scratch/kgurupra/APR14/mw8133/wlserver_10.3'
	DC2_WEBT11g_JDK_HOME = '/net/adcnas418/export/farm_fmwqa/java/linux64/jdk7u80'
	########################For JRF_INSTALL ################################################
	DC2_OHS12C_WGID = 'DC1WG'
	DC2_WG_OHS_PORT = '2222'
	DC2_OHS12C_HOSTNAME = 'slc09cor.us.oracle.com'
	DC2_RREG_OUTPUT =''
	########################For JRF_INSTALL ################################################
	DC2_JRF_INSTALL_JDK_HOME = '/ade_autofs/gd29_3rdparty/JDK8_MAIN_LINUX.X64.rdd/LATEST/jdk8/'
	DC2_JRF_INSTALL_MW_HOME = '/scratch/kgurupra/APR14/mw4522/wlserver'
	DC2_JRF_SHIPHOME = '/ade/kgurupra_dte2941/oracle/work/JRF_INSTALL/stage/fmw_12.2.1.3.0_infrastructure_generic.jar'
	########################For FMW_OHS_INST1 ################################################
	DC2_OHS12C_ORACLE_HOME = '/scratch/kgurupra/APR14/ohs6725'
	DC2_OHS12C_INSTALL_TYPE = 'STANDALONE'
	########################For FMW_OHS_INST1 ################################################
	DC2_OHS12C_ORACLE_HOME = '/scratch/kgurupra/APR14/ohs6725'
	DC2_OHS12C_INSTALL_TYPE = 'STANDALONE'
	DC2_NODEMGR_PORT = '5556'
	########################For Create_Standalone_Instance ################################################
	DC2_OHS12C_WLS_USER = 'weblogic'
	DC2_OHS12C_WLS_PWD = 'welcome1'
	DC2_OHS12C_WLS_DOMAIN_NAME = 'OHSDomain_standa2'
	DC2_OHS_INSTANCE_NAME = 'standal_ohs2'
	DC2_OHS12C_WLS_DOMAIN_HOME = '/scratch/kgurupra/APR14/ohs6725/user_projects/domains/OHSDomain_standa2'
	DC2_OHS12C_MW_HOME = '/scratch/kgurupra/APR14/ohs6725'
	DC2_OHS12C_ADMIN_PORT = '1111'
	DC2_OHS12C_LISTEN_PORT = '2222'
	DC2_OHS12C_SSL_LISTEN_PORT = '3333'
	######################## For  FIAT ################################################
	MDC_ATTR = '/ade/kgurupra_dte2941/oracle/work/config.properties'
	########################For DATABASE BLOCK ################################################
	DC3_DB_HOSTNAME = 'slc09cor.us.oracle.com'
	DC3_DB_ORACLE_HOME = '/scratch/kgurupra/APR14/db6075'
	DC3_DB_ORACLE_SID = 'db6075'
	DC3_DB_GLOBAL_DB_NAME = 'db6075.us.oracle.com'
	DC3_DB_DB_PORT = '11378'
	DC3_DB_SYS_PASSWORD = 'welcome1'
	DC3_DB_CONNECTION_STRING = 'slc09cor.us.oracle.com:11378:db6075'
	########################For RCUPHASE  BLOCK ################################################
	DC3_COMMON_ORACLE_HOME = '/scratch/kgurupra/APR14/mw33/oracle_common'
	DC3_DB_OAM_SCHEMANAME = 'db6075_OAM'
	########################For IDM_NEXTGEN_CONFIG1 BLOCK ################################################
	DC3_OAM_PROXYPORT = '5575'
	DC3_WLS_USER = 'weblogic'
	DC3_WLS_PWD = 'weblogic1'
	DC3_WLS_DOMAIN_NAME = 'WLS_IDM'
	DC3_MW_HOME = '/scratch/kgurupra/APR14/mw33'
	DC3_WL_HOME = '/scratch/kgurupra/APR14/mw33/wlserver'
	DC3_ORACLE_HOME = '/scratch/kgurupra/APR14/mw33/idm'
	DC3_WLS_DOMAIN_HOME = '/scratch/kgurupra/APR14/mw33/user_projects/domains/WLS_IDM'
	DC3_WLS_CONSOLE_PORT = '21226'
	DC3_WLS_CONSOLE_SSLPORT = '15458'
	DC3_HOSTNAME = 'slc09cor.us.oracle.com'
	DC3_ADMIN_SERVER_NAME = 'AdminServer'
	DC3_COMMON_ORACLE_HOME = '/scratch/kgurupra/APR14/mw33/oracle_common'
	DC3_SHUTDOWN_SCRIPT = '/scratch/kgurupra/APR14/mw33/idm/shutdown.csh'
	DC3_FRONT_END_PORT =''
	DC3_FRONT_END_HOST =''
	DC3_OAM_MNGSERVER_NAME = 'oam_server1'
	DC3_OAM_MNGSERVER_PORT = '24618'
	DC3_OAM_MNGSERVER_SSL_PORT = '15011'
	DC3_OAMPOL_MNGSERVER_NAME = 'oam_policy_mgr1'
	DC3_OAMPOL_MNGSERVER_PORT = '18230'
	DC3_OAMPOL_MNGSERVER_SSL_PORT = '24786'
	DC3_OAM_MNGSERVER2_NAME =''
	DC3_OAM_MNGSERVER2_PORT =''
	DC3_OAM_MNGSERVER2_SSL_PORT =''
	DC3_OAMPOL_MNGSERVER2_NAME =''
	DC3_OAMPOL_MNGSERVER2_PORT =''
	DC3_OAMPOL_MNGSERVER2_SSL_PORT =''
	########################For OID info################################################
	DC3_OID_DOMAIN_HOME =''
	DC3_OID_HOSTNAME =''
	DC3_LDAP_SSL_PORT =''
	DC3_LDAP_NONSSL_PORT =''
	DC3_OID_INSTANCE_HOME =''
	DC3_OID_ADMIN_PASSWORD =''
	DC3_OID_USER =''
	DC3_OID_NAMESPACE =''
	########################For 11g OHS&WG info################################################
	DC3_WEBT11g_WL_HOME = '/scratch/kgurupra/APR14/mw8133/wlserver_10.3'
	DC3_WEBT11g_JDK_HOME = '/net/adcnas418/export/farm_fmwqa/java/linux64/jdk7u80'
	########################For JRF_INSTALL ################################################
	DC3_OHS12C_WGID = 'DC1WG'
	DC3_WG_OHS_PORT = '2222'
	DC3_OHS12C_HOSTNAME = 'slc09cor.us.oracle.com'
	DC3_RREG_OUTPUT =''
	########################For JRF_INSTALL ################################################
	DC3_JRF_INSTALL_JDK_HOME = '/ade_autofs/gd29_3rdparty/JDK8_MAIN_LINUX.X64.rdd/LATEST/jdk8/'
	DC3_JRF_INSTALL_MW_HOME = '/scratch/kgurupra/APR14/mw4522/wlserver'
	DC3_JRF_SHIPHOME = '/ade/kgurupra_dte2941/oracle/work/JRF_INSTALL/stage/fmw_12.2.1.3.0_infrastructure_generic.jar'
	########################For FMW_OHS_INST1 ################################################
	DC3_OHS12C_ORACLE_HOME = '/scratch/kgurupra/APR14/ohs6725'
	DC3_OHS12C_INSTALL_TYPE = 'STANDALONE'
	########################For FMW_OHS_INST1 ################################################
	DC3_OHS12C_ORACLE_HOME = '/scratch/kgurupra/APR14/ohs6725'
	DC3_OHS12C_INSTALL_TYPE = 'STANDALONE'
	DC3_NODEMGR_PORT = '5556'
	########################For Create_Standalone_Instance ################################################
	DC3_OHS12C_WLS_USER = 'weblogic'
	DC3_OHS12C_WLS_PWD = 'welcome1'
	DC3_OHS12C_WLS_DOMAIN_NAME = 'OHSDomain_standa2'
	DC3_OHS_INSTANCE_NAME = 'standal_ohs2'
	DC3_OHS12C_WLS_DOMAIN_HOME = '/scratch/kgurupra/APR14/ohs6725/user_projects/domains/OHSDomain_standa2'
	DC3_OHS12C_MW_HOME = '/scratch/kgurupra/APR14/ohs6725'
	DC3_OHS12C_ADMIN_PORT = '1111'
	DC3_OHS12C_LISTEN_PORT = '2222'
	DC3_OHS12C_SSL_LISTEN_PORT = '3333'
	######################## For  FIAT ################################################
	MDC_ATTR = '/ade/kgurupra_dte2941/oracle/work/config.properties'
	######################## For  FIAT ################################################
	MDC_ATTR = '/ade/kgurupra_dte2941/oracle/work/config.properties'
	########################For CFG_RESOURCE_WG ################################################
	OHS_INSTANCE1_WLS_USER = 'weblogic'
	RWG_NODEMGR_PORT = '5556'
	OHS_INSTANCE1_WLS_PWD = 'welcome1'
	RWG_WG1_HOSTNAME = 'slc12pcc.us.oracle.com'
	RWG_WG2_HOSTNAME = 'slc12pcc.us.oracle.com'
	RWG_WG3_HOSTNAME = 'slc12pcc.us.oracle.com'
	RWG_WG4_HOSTNAME =''
	OHS_INSTANCE1_WLS_DOMAIN_NAME = 'OHSDomain_rwg'
	OHS_INSTANCE1_WLS_DOMAIN_HOME = '/scratch/kgurupra/APR14/ohs1932/user_projects/domains/OHSDomain_rwg'
	OHS_INSTANCE1_MW_HOME = '/scratch/kgurupra/APR14/ohs1932'
	OHS_INSTANCE1_WL_HOME = '/scratch/kgurupra/APR14/ohs1932/wlserver'
	OHS_INSTANCE1_COMMON_ORACLE_HOME = '/scratch/kgurupra/APR14/ohs1932/oracle_common'
	OHS_INSTANCE1_OHS_INSTANCE_NAME = 'rwg6222'
	OHS_INSTANCE1_LISTEN_PORT = '6222'
	OHS_INSTANCE1_SSL_LISTEN_PORT = '6223'
	OHS_INSTANCE1_ADMIN_PORT = '6221'
	OHS_INSTANCE1_WGID = 'WG6222'
	OHS_INSTANCE1_WG_PORT = '6222'
	OHS_INSTANCE2_WLS_USER = 'weblogic'
	OHS_INSTANCE2_WLS_PWD = 'welcome1'
	OHS_INSTANCE2_WLS_DOMAIN_NAME = 'OHSDomain_rwg'
	OHS_INSTANCE2_WLS_DOMAIN_HOME = '/scratch/kgurupra/APR14/ohs1932/user_projects/domains/OHSDomain_rwg'
	OHS_INSTANCE2_MW_HOME = '/scratch/kgurupra/APR14/ohs1932'
	OHS_INSTANCE2_WL_HOME = '/scratch/kgurupra/APR14/ohs1932/wlserver'
	OHS_INSTANCE2_COMMON_ORACLE_HOME = '/scratch/kgurupra/APR14/ohs1932/oracle_common'
	OHS_INSTANCE2_OHS_INSTANCE_NAME = 'rwg7222'
	OHS_INSTANCE2_LISTEN_PORT = '7222'
	OHS_INSTANCE2_SSL_LISTEN_PORT = '7223'
	OHS_INSTANCE2_ADMIN_PORT = '7221'
	OHS_INSTANCE2_WGID = 'WG7222'
	OHS_INSTANCE2_WG_PORT = '7222'
	OHS_INSTANCE3_WLS_USER = 'weblogic'
	OHS_INSTANCE3_WLS_PWD = 'welcome1'
	OHS_INSTANCE3_WLS_DOMAIN_NAME = 'OHSDomain_rwg'
	OHS_INSTANCE3_WLS_DOMAIN_HOME = '/scratch/kgurupra/APR14/ohs1932/user_projects/domains/OHSDomain_rwg'
	OHS_INSTANCE3_MW_HOME = '/scratch/kgurupra/APR14/ohs1932'
	OHS_INSTANCE3_WL_HOME = '/scratch/kgurupra/APR14/ohs1932/wlserver'
	OHS_INSTANCE3_COMMON_ORACLE_HOME = '/scratch/kgurupra/APR14/ohs1932/oracle_common'
	OHS_INSTANCE3_OHS_INSTANCE_NAME = 'rwg8222'
	OHS_INSTANCE3_LISTEN_PORT = '8222'
	OHS_INSTANCE3_SSL_LISTEN_PORT = '8223'
	OHS_INSTANCE3_ADMIN_PORT = '8221'
	OHS_INSTANCE3_WGID = 'WG8222'
	OHS_INSTANCE3_WG_PORT = '8222'
	OHS_INSTANCE4_WLS_USER = 'weblogic'
	OHS_INSTANCE4_WLS_PWD = 'welcome1'
	OHS_INSTANCE4_WLS_DOMAIN_NAME = 'OHSDomain_rwg'
	OHS_INSTANCE4_WLS_DOMAIN_HOME = '/scratch/kgurupra/APR14/ohs1932/user_projects/domains/OHSDomain_rwg'
	OHS_INSTANCE4_MW_HOME = '/scratch/kgurupra/APR14/ohs1932'
	OHS_INSTANCE4_WL_HOME = '/scratch/kgurupra/APR14/ohs1932/wlserver'
	OHS_INSTANCE4_COMMON_ORACLE_HOME = '/scratch/kgurupra/APR14/ohs1932/oracle_common'
	OHS_INSTANCE4_OHS_INSTANCE_NAME = 'rwg9222'
	OHS_INSTANCE4_LISTEN_PORT = '9222'
	OHS_INSTANCE4_SSL_LISTEN_PORT = '9223'
	OHS_INSTANCE4_ADMIN_PORT = '9221'
	OHS_INSTANCE4_WGID = 'WG9222'
	OHS_INSTANCE4_WG_PORT = '9222'


def __init__(self):
	self.another_variable = 'another value'
